[package]
name = "asserhttp"
version = "0.2.3"
edition = "2021"
authors = ["Beltram Maldant"]
description = "Fluent http response assertions"
homepage = "https://github.com/beltram/asserhttp"
repository = "https://github.com/beltram/asserhttp"
license = "Apache-2.0"
keywords = ["test", "http", "client", "actix", "reqwest"]
categories = ["development-tools::testing", "api-bindings", "web-programming::http-client"]

include = ["/src/*", "/tests/*", "/Cargo.toml"]

[dependencies]
anyhow = "1.0.51"
async-std = "1.10.0"
serde = "1.0.130"
serde_json = "1.0.72"
regex = "1.4.6"
surf = { version = "2.3.2", optional = true }
isahc = { version = "1.6.0", features = ["json"], optional = true }
reqwest = { version = "0.11.7", features = ["json", "blocking"], optional = true }
hyper = { version = "0.14.15", features = ["client"], optional = true }
awc = { version = "2.0.3", optional = true }
actix-http = { version = "2.2.1", optional = true }
actix-web = { version = "3.3.2", optional = true }

[dev-dependencies]
asserhttp = { path = ".", features = ["surf", "isahc", "reqwest", "hyper", "actix"] }
stubr = "0.4.11"
serde_json = "1.0.72"
async-std = { version = "1.10.0", features = ["attributes"] }
tokio = { version = "1.14.0", features = ["macros"] }
actix-rt = "1.1.1"

[features]
default = []
actix = ["awc", "actix-http", "actix-web"]