[package]
name = "asserhttp"
version = "0.3.0"
edition = "2021"
authors = ["Beltram Maldant"]
description = "Fluent http response assertions"
homepage = "https://github.com/beltram/asserhttp"
repository = "https://github.com/beltram/asserhttp"
license = "Apache-2.0"
keywords = ["test", "http", "client", "actix", "reqwest"]
categories = ["development-tools::testing", "api-bindings", "web-programming::http-client"]

include = ["/src/*", "/tests/*", "/Cargo.toml"]

[dependencies]
anyhow = "1.0.55"
async-std = "1.10.0"
serde = "1.0.136"
serde_json = "1.0.79"
regex = "1.4.6"
http-types = "2.12.0"
surf = { version = "2.3.2", optional = true }
isahc = { version = "1.6.0", features = ["json"], optional = true }
reqwest = { version = "0.11.9", features = ["json", "blocking"], optional = true }
hyper = { version = "0.14.17", features = ["client"], optional = true }
awc = { version = "3.0.0-beta.21", optional = true }
actix-http = { version = "3.0.0", optional = true }
actix-web = { version = "4.0.1", optional = true }
rocket = { version = "0.5.0-rc.1", optional = true }

[dev-dependencies]
asserhttp = { path = ".", features = ["surf", "isahc", "reqwest", "hyper", "actix", "rocket"] }
stubr = "0.4.14"
serde_json = "1.0.79"
async-std = { version = "1.10.0", features = ["attributes"] }
tokio = { version = "1.16.1", features = ["macros"] }
actix-rt = "2.6.0"
pin-project = "1.0.10"
rocket = { version = "0.5.0-rc.1", features = ["json"] }

[features]
default = []
actix = ["awc", "actix-http", "actix-web"]

[profile.dev]
# improves compilation performances on macos
split-debuginfo = "unpacked"