[package]
name = "asserhttp"
version = "0.4.2"
edition = "2021"
authors = ["Beltram Maldant"]
description = "Fluent http response assertions"
homepage = "https://github.com/beltram/asserhttp"
repository = "https://github.com/beltram/asserhttp"
license = "Apache-2.0"
keywords = ["test", "http", "client", "actix", "reqwest"]
categories = ["development-tools::testing", "api-bindings", "web-programming::http-client"]

include = ["/src/*", "/tests/*", "/Cargo.toml"]

[dependencies]
anyhow = "1.0.57"
futures-lite = { version = "1.12.0", features = ["std"], default-features = false }
serde = "1.0.136"
serde_json = "1.0.79"
regex = { version = "1.5.5", features = ["std", "unicode"], default-features = false }
http-types = { version = "2.12.0", default-features = false }
surf = { version = "2.3.2", optional = true, features = ["curl-client"], default-features = false }
isahc = { version = "1.7.0", features = ["json", "text-decoding"], optional = true, default-features = false }
reqwest = { version = "0.11.10", features = ["json", "blocking"], optional = true, default-features = false }
hyper = { version = "0.14.18", features = ["client"], optional = true, default-features = false }
awc = { version = "3.0.0", optional = true, default-features = false }
actix-http = { version = "3.0.4", optional = true, default-features = false }
actix-web = { version = "4.0.1", optional = true, default-features = false }
rocket = { version = "0.5.0-rc.1", optional = true, default-features = false }

[dev-dependencies]
asserhttp = { path = ".", features = ["surf", "isahc", "reqwest", "hyper", "actix", "actix-web-client", "rocket"] }
actix-web = { version = "4.0.1", features = ["macros"], default-features = false }
stubr = "0.4.14"
serde_json = "1.0.79"
async-std = { version = "1.11.0", features = ["attributes"] }
tokio = { version = "1.17.0", features = ["macros"] }
pin-project = "1.0.10"
rocket = { version = "0.5.0-rc.1", features = ["json"] }
paste = "1.0.7"

[features]
default = []
actix = ["actix-http", "actix-web"]
actix-web-client = ["awc", "actix-http/ws"]

[profile.dev]
# improves compilation performances on macos
split-debuginfo = "unpacked"