[package]
name = "asserhttp"
version = "0.0.1"
edition = "2018"
authors = ["Beltram Maldant"]
description = "Fluent http assertions"
homepage = "https://github.com/beltram/asserhttp"
repository = "https://github.com/beltram/asserhttp"
license = "Apache-2.0"
keywords = ["test", "http", "client", "testing"]
categories = ["development-tools::testing", "api-bindings"]

include = ["/src/*", "/tests/*", "/Cargo.toml"]

[dependencies]
surf = "2.2.0"
isahc = "1.4.0"

[dev-dependencies]
stubr = "0.4.3"

[dev-dependencies.async-std]
version = "1.9.0"
features = ["attributes"]