[package]
name = "asserhttp"
version = "0.0.1"
edition = "2018"

[dependencies]
surf = "2.2.0"
isahc = "1.4.0"

[dev-dependencies]
stubr = "0.4.3"

[dev-dependencies.async-std]
version = "1.9.0"
features = ["attributes"]