[package]
name = "asserhttp"
version = "0.0.2"
edition = "2018"
authors = ["Beltram Maldant"]
description = "Fluent http assertions"
homepage = "https://github.com/beltram/asserhttp"
repository = "https://github.com/beltram/asserhttp"
license = "Apache-2.0"
keywords = ["test", "http", "client", "testing"]
categories = ["development-tools::testing", "api-bindings"]

include = ["/src/*", "/tests/*", "/Cargo.toml"]

[dependencies]
anyhow = "1.0.41"
async-std = "1.9.0"
serde = "1.0.126"
surf = { version = "2.2.0", optional = true }
isahc = { version = "1.4.0", features = ["json"], optional = true }

[dev-dependencies]
stubr = "0.4.4"
serde_json = "1.0.64"

[dev-dependencies.async-std]
version = "1.9.0"
features = ["attributes"]

[features]
default = ["surf", "isahc"]