name: ci

on: [ push, pull_request ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: taiki-e/install-action@cargo-hack
      - uses: Swatinem/rust-cache@v1
      - name: cargo/hack (verify features compile in isolation)
        run: cargo hack check --each-feature --no-dev-deps
      - name: cargo/test
        run: cargo test
      - name: cargo/clippy
        run: cargo clippy
  publish:
    # runs on tags only
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: publish
        run: cargo publish --token ${{ secrets.CRATES_IO_TOKEN }}